let prisma = null;
let demoMode = false;
try {
  // eslint-disable-next-line global-require
  const { PrismaClient } = require("@prisma/client");
  prisma = new PrismaClient();
} catch (err) {
  // The Prisma client is generated by `prisma generate` (postinstall). If it
  // hasn't been generated yet (e.g. a dev preview without a database), fall back
  // to a stub so the server can still boot and serve the static site. Public
  // API routes serve built-in demo content instead of failing (see
  // server/controllers/public.controller.js), so the site renders without
  // errors. Every real DB query rejects with a clear message.
  // eslint-disable-next-line no-console
  console.warn("[prisma] Prisma client unavailable — running in demo mode (no database).");
  console.warn("        Public pages serve sample content. Run `npm run setup` to enable the database.");

  demoMode = true;

  const ERR = new Error(
    "Database is not configured. Run `npm install`, `npx prisma generate` and `npm run db:push`, then start the server."
  );

  const reject = () => Promise.reject(ERR);
  // Recursive proxy so chains like prisma.user.findMany(...) work and reject.
  const make = () => new Proxy(reject, {
    get: (target, prop) => {
      if (prop === "demoMode") return demoMode;
      if (prop === "then") return undefined; // keep it non-thenable
      return make();
    },
    apply: () => Promise.reject(ERR),
  });
  prisma = make();
}

// Lets routes detect demo mode without throwing on every query.
prisma.demoMode = demoMode;

module.exports = prisma;
